export default interface ProjectModel {
  id: number,
  title: string,
  content: string,
  image: string,
  preview: string,
  reserve_link: string,
  video_link: string,
  traded_instruments: string,
  investments: string,
  profit: string,
  risk: string,
  deadlines: string,
  start: string,
  about_project: string,
  top: string,
  active: string,
  sort: number,
  benefits: string,
  created_at: string,
  updated_at: string,
  slug: string,
  referral_link: string
}
